### ISSUE TITLE
Incorrect display of hidden SSID status

### ISSUE THREAD

**Issue by marvellz** [TrueMLGPro/Wi-Fi_Info#51]
- [x] I am running the latest app version (Ver. app: 1.6)
- [x] I checked to make sure that issue has not already been filled

**Describe the bug**
Incorrect display of hidden network status.

**To Reproduce**
Run the app, look at the **block SSID, BSSID, etc**.

I tried on two different networks.
I forgot the network and reconnected to it after installing the app, it still displays - **No**.
Tested it in two different languages, thought translation difficulties, but with different languages - **No**.

![Screenshot_2023-08-31-11](https://github.com/TrueMLGPro/Wi-Fi_Info/assets/48913829/62b490f2-d9b8-4655-a693-d1ff3147680b)

**Expected behavior**
This line **Hidden SSID** should be **Yes**.

**Smartphone:**
 - Device: 📱 Realme on RealmeUI 4.0 (this is one of the cleanest firmware)
 - OS: Android 13, SDK 33

**Comment by TrueMLGPro** [comment]
Hello, thank you for reporting this! I've never really been able to test the hidden SSID detection.
Turns out that when you connect to the Wi-Fi network configured to have a hidden SSID, it starts broadcasting its SSID to the device which connects to it, thus making the app show that the network "doesn't have its SSID hidden". So it actually draws the Hidden SSID field useless...

![Hidden SSID field doesn't work](https://github.com/TrueMLGPro/Wi-Fi_Info/assets/38999995/e7e12dea-5d72-403d-aaff-89488ce1d1fb)
